### ISSUE TITLE
Micro VMI plugin error

### ISSUE THREAD

**Issue by AtomicBool** [ufrisk/LeechCore-plugins#8]
When tring to call scatterexcute or VMMDLL_MemWrite
But Read Functions working

Host: manjaro arch (linux 6.0.1)
Guest: Windows 11 23H2 (22631)
Memflow connector: memflow-qemu
Build from https://github.com/ufrisk/LeechCore-plugins/blob/master/leechcore_device_microvmi/leechcore_device_microvmi.c
and the libmicrovmi.h was copied from https://github.com/Wenzel/libmicrovmi

Includes:
vmm.so
leechcore.so
leechcore_device_microvmi.so
libmicrovmi.so
libmemflow_qemu.x86_64.so

Output:
thread '<unnamed>' panicked at src/api/mod.rs:87:9:
not implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

**Comment by ufrisk** [comment]
Since it's a rust panic it's probably an issue with microvmi or the memflow connector and not LeechCore. Neither those are part of this project and I'm afraid I won't be able to help with that. If you wish to use this approach you may have to create an issue in the microvmi project.

MemProcFS/LeechCore also support a direct native connection to QEMU. There is usually no need to do the detour with microvmi+memflow, but I recon it would depend on your setup. If you're able to configure your VM with shared memory or huge pages you could do it natively with LeechCore. Check out: https://github.com/ufrisk/LeechCore/wiki/Device_QEMU

**Comment by AtomicBool** [comment]
> Since it's a rust panic it's probably an issue with microvmi or the memflow connector and not LeechCore. Neither those are part of this project and I'm afraid I won't be able to help with that. If you wish to use this approach you may have to create an issue in the microvmi project.
> 
> MemProcFS/LeechCore also support a direct native connection to QEMU. There is usually no need to do the detour with microvmi+memflow, but I recon it would depend on your setup. If you're able to configure your VM with shared memory or huge pages you could do it natively with LeechCore. Check out: https://github.com/ufrisk/LeechCore/wiki/Device_QEMU

yes,  

> When tring to call scatterexcute or VMMDLL_MemWrite But Read Functions working
> 
> Host: manjaro arch (linux 6.0.1) Guest: Windows 11 23H2 (22631) Memflow connector: memflow-qemu Build from https://github.com/ufrisk/LeechCore-plugins/blob/master/leechcore_device_microvmi/leechcore_device_microvmi.c and the libmicrovmi.h was copied from https://github.com/Wenzel/libmicrovmi
> 
> Includes: vmm.so leechcore.so leechcore_device_microvmi.so libmicrovmi.so libmemflow_qemu.x86_64.so
> 
> Output: thread '' panicked at src/api/mod.rs:87:9: not implemented note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace fatal runtime error: failed to initiate panic, error 5

I found that microvmi don't have function for memflow write

> When tring to call scatterexcute or VMMDLL_MemWrite But Read Functions working
> 
> Host: manjaro arch (linux 6.0.1) Guest: Windows 11 23H2 (22631) Memflow connector: memflow-qemu Build from https://github.com/ufrisk/LeechCore-plugins/blob/master/leechcore_device_microvmi/leechcore_device_microvmi.c and the libmicrovmi.h was copied from https://github.com/Wenzel/libmicrovmi
> 
> Includes: vmm.so leechcore.so leechcore_device_microvmi.so libmicrovmi.so libmemflow_qemu.x86_64.so
> 
> Output: thread '' panicked at src/api/mod.rs:87:9: not implemented note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace fatal runtime error: failed to initiate panic, error 5

I found out, microvmi don't have function for memflow write.
